name = "social-feed-worker"
main = "./src/index.ts"
compatibility_date = "2024-04-29"
logpush = true

[vars]
CONTEMBER_BASE_API_URL = "http://localhost:1481"
CONTEMBER_PROJECT_SLUG = "social-feed"

# [secrets]
# CONTEMBER_API_TOKEN
# CONTEMBER_ACTIONS_SECRET_KEY
